server:
  port: 8082

spring:
  application:
    name: security-service

  datasource:
    url: jdbc:postgresql://localhost:5433/hrm_user
    username: postgres
    password: dangquang1009
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
