server:
  port: 8083

spring:
  application:
    name: common-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm.microservices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
