server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm.microservices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

