server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dngKwngg/hrm.microservices
          search-paths:
            - config/user-service.yml
            - config/department-service.yml
            - config/gateway-server.yml
            - config/common-service.yml
          clone-on-start: true