server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dngKwngg/spring-cloud-config-server-hrm.git
          clone-on-start: true



